In [1]:
%load_ext autoreload
%autoreload 2

In [1]:
import logging 

logging.basicConfig(level=logging.INFO)

In [1]:
from sentence_transformers import SentenceTransformer
from raggler.rag import create_index


model = SentenceTransformer('paraphrase-albert-small-v2')

index  = create_index(['../tests/fake_files/','../tests/more_fake_files/'], embedder=model, path_to_save_index='../tests/test_index/')

  0%|          | 0/2 [00:00<?, ?it/s]

In [2]:
from sentence_transformers import SentenceTransformer

from raggler.rag import RAG

from raggler.mlx_llm import MLXLLM
from raggler.llm_context import RAG_TEMPLATE
model = SentenceTransformer('paraphrase-albert-small-v2')

test = MLXLLM("mlx-community/NeuralBeagle14-7B-4bit-mlx", prompt_template=RAG_TEMPLATE)


# TODO Too much input; we can give one path for both index and content. 
rag = RAG(embedder=model, index = index, language_model=test)

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]

In [3]:
rag('Do you know any poems about retrieval augmented generation?', print_context=False)

The provided context includes a poem written about Gemini Advanced, which touches upon the concepts of retrieval and augmented generation. Here it is again for reference:

No longer bound by learned terrain,
The model seeks where wisdom may remain.
Not from its depths, but knowledge stores so vast,
It finds the context, shadows from the past.

No simple guess, no fabricated lore,
But retrieved

KeyboardInterrupt: 

In [4]:
rag.faiss_index.search(query_vect, 1)

In [11]:
[x.page_content for x in sentences]

NameError: name 'sentences' is not defined

In [ ]:
all_vectors.shape

(3, 768)

In [15]:
rag.faiss_index.id_map

AttributeError: 'IndexFlat' object has no attribute 'id_map'

In [3]:
import faiss 
index = faiss.IndexIDMap2(faiss.IndexFlatL2(768))

import numpy as np
ids = np.random.randint(0, 5000, size=3)
x = np.random.rand(3, 768).astype('float32')
index.add_with_ids(x, ids)  

In [4]:
faiss.vector_to_array(index.id_map)


array([2508, 3811, 3317])

In [3]:
ids

array([ 699, 1580, 4858, 3749, 2042, 4918, 1289, 1026,  387, 3617])

In [5]:
D, I = index.search(x[0:1], 1)

In [8]:
x[0:1]

array([[0.42649946, 0.8683235 , 0.27395678, 0.981551  , 0.93993247,
        0.7196041 , 0.39098695, 0.67844146, 0.17187141, 0.33504173,
        0.9903376 , 0.10003801, 0.02977539, 0.71505463, 0.9506187 ,
        0.8890744 , 0.2968436 , 0.40890726, 0.23552068, 0.5886054 ,
        0.0078138 , 0.24500987, 0.74164534, 0.9515231 , 0.2796087 ,
        0.76148665, 0.9435544 , 0.80855584, 0.18041989, 0.9077724 ,
        0.42793778, 0.13020644, 0.06331004, 0.03389155, 0.24444655,
        0.90742356, 0.40878835, 0.81563383, 0.53018266, 0.2518977 ,
        0.34092137, 0.33835274, 0.4378197 , 0.28661755, 0.9112174 ,
        0.9983474 , 0.22428498, 0.7179647 , 0.86955214, 0.3507455 ,
        0.99250907, 0.5125487 , 0.72075284, 0.893607  , 0.9226142 ,
        0.52199304, 0.7624732 , 0.51512283, 0.06519125, 0.7155395 ,
        0.6076641 , 0.8805598 , 0.6165368 , 0.9017079 , 0.15197471,
        0.66930425, 0.33847362, 0.7611637 , 0.6373309 , 0.7176475 ,
        0.2559423 , 0.9176608 , 0.0431858 , 0.24

In [12]:
x[0:1]

array([[0.9490831 , 0.39238948, 0.5134076 , 0.12559897, 0.48252553,
        0.46649912, 0.15210135, 0.5695138 , 0.12272299, 0.8125082 ,
        0.89328796, 0.25748855, 0.54151076, 0.6635538 , 0.9572456 ,
        0.45839798, 0.59353757, 0.12463374, 0.19493997, 0.13007435,
        0.4990173 , 0.6664736 , 0.48981133, 0.35219157, 0.06123954,
        0.6094326 , 0.7866891 , 0.1868274 , 0.4002945 , 0.8737481 ,
        0.47977135, 0.41355634]], dtype=float32)